version: '2'
services:
    laitecatholic-app:
        image: laitecatholic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://laitecatholic-mysql:3306/laitecatholic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    laitecatholic-mysql:
        extends:
            file: mysql.yml
            service: laitecatholic-mysql
